name: .NET
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.400

    - name: Restore dependencies NET 8
      run: dotnet restore -p:TargetFramework=net8.0
    
    - name: Build NET 8
      run: dotnet build -p:TargetFramework=net8.0 --no-restore

    - name: Test NET 8
      run: dotnet test -p:TargetFramework=net8.0 --no-build --verbosity normal

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
